--- #YAML:1.0
name:               AnyEvent-Ping-TCP
version:            1.00
abstract:           Asynchronous and Synchronous TCP ping functions.
author:
    - Phillip O'Donnell <podonnell@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
