---
abstract: 'Asynchronous and Synchronous TCP ping functions.'
author:
  - "Phillip O'Donnell <podonnell@cpan.org>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Ping-TCP
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 7
  Time::HiRes: 1.9719
version: 1.01
